package com.sharenote.audit;

public enum AuditAction {
    USER_REGISTERED,
    PROFILE_PICTURE_UPDATED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    REFRESH_TOKEN_USED,
    NOTE_UPLOADED,
    COMMENT_CREATED,
    REPLY_CREATED,
    NOTE_UPVOTED,
    TAKE_A_LOOK_SUGGESTED,
    NOTIFICATION_READ,
    NOTIFICATIONS_READ_ALL,
    USER_TEMPORARILY_BANNED,
    USER_PERMANENTLY_BANNED,
    USER_UNBANNED
}
